### ISSUE TITLE
FR: Change the shape of a conveyor when there is another conveyor next to it.

### ISSUE THREAD

**Issue by calloatti** [CottonMC/UnitedConveyors#1]
Now:

![image](https://user-images.githubusercontent.com/12817862/63633297-88eb0b80-c61c-11e9-98ad-fa56d1deaf75.png)

Maybe it looks better this way:

![image](https://user-images.githubusercontent.com/12817862/63633298-9a341800-c61c-11e9-8bfc-acbdc04dc9c0.png)

It would look even better if the conveyor "siding" on the side where its next to the other conveyor was removed too, but my MS Paint skills only go so far.

**Comment by falkreon** [comment]
I can "snap" the conveyor when there's one pointed at it, sure. I can not drop the side-wall without adding BlockStates, which I'm not doing. Maybe some day Exotic Matter will make more complicated connections possible, but not today.

**Comment by falkreon** [comment]
Fixed in dev
