### ISSUE TITLE
Crash when placing a Stockpile barrel next to a conveyor

### ISSUE THREAD

**Issue by calloatti** [CottonMC/UnitedConveyors#2]
**Describe the bug**
When placing a barrel from https://www.curseforge.com/minecraft/mc-mods/stockpile next to a conveyor, MC crashes.

https://paste.ee/p/Jt3Q9

> java.lang.IllegalArgumentException: You should never test an IItemFilter with an empty stack!

**To Reproduce**
Place a barrel from stockpile in front of a conveyor, so the barrel gets the output of the conveyor

**Expected behavior** *Optional*
MC not crashing

**Version of the (please complete the following information):**
MC 1.14.4
stockpile-1.1.0+1.14.4.jar
UnitedConveyors-0.0.1.jar (built from source)
fabric-api-0.3.2+build.218-1.14.jar

**Additional context** *Optional*

**Comment by LemmaEOF** [comment]
Hm, this looks like a function of LBA's item filter system. It doesn't like having an empty item stack tested against a filter, for some reason. I don't think it's right of it to throw, though.
