### ISSUE TITLE
Dupe bug when dropping item on conveyors

### ISSUE THREAD

**Issue by calloatti** [CottonMC/UnitedConveyors#3]
**Describe the bug**
Sometimes an item dropped in a conveyor gets duplicated.

**To Reproduce**
Watch the video: https://streamable.com/zyy00

**Expected behavior** *Optional*
No duplicated items.

UnitedConveyors-0.0.1.jar built from source.

**Comment by LemmaEOF** [comment]
Looks to me like the entity is being nabbed by another conveyor before it gets killed off by the server. That looks like it’d be a fun race condition to solve.

**Comment by falkreon** [comment]
Can we confirm that what arrives in the chest *actually* winds up duped?
* If it's cosmetic, it's pretty low priority
* If it's not, it's really high priority

**Comment by metoray** [comment]
I tested it in singleplayer, the item does actually get duped.

**Comment by falkreon** [comment]
Alright, I think this is actually a pretty straightforward fix

**Comment by falkreon** [comment]
Should be fixed by 2a6c39a - please reopen this if I'm mistaken.
